//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Required(ErrorMessage ="Id is required")]
        public int Id { get; set; }
       [Required(ErrorMessage ="Name is required") ]
        public string Name { get; set; }
        public string Address { get; set; }
        [Range(20,60,ErrorMessage ="Age should be between 20 to 60")]
        public int Age { get; set; }
        [EmailAddress(ErrorMessage = "Invalid Email Address.")]
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<int> StateId { get; set; }
        public string hobbies { get; set; }
      
        public virtual State State { get; set; }
    }
}
